### ISSUE TITLE
Releases not properly marked on github

### ISSUE THREAD

**Issue by hakan42** [m4v/RCSBuildAid#20]
For reasons unknown to me, your releases are not shown on the github api:

```
root@ksp-ckan:~# curl https://api.github.com/repos/m4v/RCSBuildAid/releases
[

]
```

Could you please check whether you need to write additional text on your releases?

**Comment by m4v** [comment]
I didn't do any releases in github, I just push code.

**Comment by m4v** [comment]
although github assumes that my tags are releases and shows them here, https://github.com/m4v/RCSBuildAid/releases

dunno.

**Comment by m4v** [comment]
okay figured it out, had to push the publish button.
https://github.com/m4v/RCSBuildAid/releases/tag/v0.5.5

Might or might not do that again next time.

**Comment by hakan42** [comment]
Ah, o.k., then our assumption that you publish binary releases on github is clearly wrong...

I guess we need to work on that curse inflator ( https://github.com/KSP-CKAN/CKAN/issues/115 ) after all :smiling_imp:
