### ISSUE TITLE
Force marker debug labels.

### ISSUE THREAD

**Issue by frencrs** [m4v/RCSBuildAid#21]
You should make the debug-feature: show vector magnitudes, available from the normal options menu.

**Comment by m4v** [comment]
ahhhm, the way I implemented it was hacky and I had all sorts of problems with it, like labels losing its parent object and floating around in the VAB, I wouldn't feel comfortable in having it as a proper feature, at least not without a rewrite.

I added it once for study a specific behaviour of RCS ports and never used it again, I never felt the need of that information when building rockets, the vector's size already tries to give an idea of the relative magnitude of forces.

**Comment by frencrs** [comment]
Huh, I haven't run into any problems with the labels. If you think just the
visual magnitude works for most users, that's fine. I just like being able
to jot down the numbers so I can compare more complex layouts without
having to eyeball it.

**Comment by m4v** [comment]
> Huh, I haven't run into any problems with the labels.

The user doesn't, is me the one that runs into problems whenever it breaks because I changed something somewhere.
