### ISSUE TITLE
Exception loading 'RCSBuildAidToolbar'

### ISSUE THREAD

**Issue by khr15714n** [m4v/RCSBuildAid#23]
Fresh install of KSP, no other mods, just RCSBuildAid

[                ] PhysicsGlobals: Loading database
[                ] Load(Assembly): /ModuleManager.2.6.8
[                ] AssemblyLoader: Loading assembly at {KSPDIR}\GameData\ModuleManager.2.6.8.dll
[                ] AssemblyLoader: KSPAssembly 'ModuleManager' V2.5
[                ] Load(Assembly): RCSBuildAid/Plugins/RCSBuildAid
[                ] AssemblyLoader: Loading assembly at {KSPDIR}\GameData\RCSBuildAid\Plugins\RCSBuildAid.dll
[                ] Load(Assembly): RCSBuildAid/Plugins/RCSBuildAidToolbar
[                ] AssemblyLoader: Loading assembly at {KSPDIR}\GameData\RCSBuildAid\Plugins\RCSBuildAidToolbar.dll
[                ] AssemblyLoader: Loading assemblies
[ERR             ] AssemblyLoader: Exception loading 'RCSBuildAidToolbar': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'RCSBuildAid.Toolbar' from assembly 'RCSBuildAidToolbar, Version=0.7.2.26995, Culture=neutral, PublicKeyToken=null'.

It seems to be working 'correct' ingame but ...

**Comment by m4v** [comment]
if you aren't going to use blizzy's toolbar, then you don't need RCSBuildAidToolbar.dll and you can delete it.
