### ISSUE TITLE
Does not support multiple RCS modules in the same part (only first one is calculated)

### ISSUE THREAD

**Issue by shadowmage45** [m4v/RCSBuildAid#26]
As per the title - only the first ModuleRCS in a part is used/checked for transforms/etc.

Will work on a proper pull request with a fix over the weekend after I can setup the repo and test out some fixes.

Seems to be caused by this break statement: https://github.com/m4v/RCSBuildAid/blob/master/Plugin/EditorUtils.cs#L43

I have not setup the project to test if removing this break has any detrimental side-effects, will be working over that in the next couple of days.

**Comment by shadowmage45** [comment]
Have started working on adapting to support multiple RCS modules on a part, and support the stock feature to disable input for specific axis.

Most things are working, should likely have something usable in a day or two.

**Comment by m4v** [comment]
I'm terribly sorry I didn't see this sooner, I must have missed the notification. What parts have multiple ModuleRCS in them?

**Comment by shadowmage45** [comment]
No stock parts that I'm aware of, but I use it quite a bit with my service module parts:

https://github.com/shadowmage45/SSTULabs/blob/master/GameData/SSTU/Parts/ShipCore/series_b/SC-B-SM.cfg#L146-L205

https://github.com/shadowmage45/SSTULabs/releases

This appears to be a new feature in stock 1.05, as it was not previously possible last I tried (0.90 or so).

PR for a 'working' implementation (not thoroughly tested for side effects), can be found at: #27  (https://github.com/m4v/RCSBuildAid/pull/27)

**Comment by m4v** [comment]
So about this bug...

This bug had to wait until I did a code rewrite, now in the development branch. This bug in particular should be fixed for the next release.
