### ISSUE TITLE
Toolbar Assembly fails to load

### ISSUE THREAD

**Issue by jkoritzinsky** [m4v/RCSBuildAid#30]
Just wanted to let you know that trying to load the RCSBuildAidToolbar assembly is failing with a ReflectionTypeLoadException in KSP 1.0.5.

**Comment by m4v** [comment]
Thats normal if you don't have blizzy's toolbar installed (see readme for link). You can remove RSCBuildAidToolbar.dll if the exception is bothering you.

**Comment by jkoritzinsky** [comment]
It was breaking my mod (since it does startup searching of subtypes) so I wanted to let you know about it.
