### ISSUE TITLE
Wrong CoM marker position when using other mods

### ISSUE THREAD

**Issue by ale260382** [m4v/RCSBuildAid#31]
Hello, i've noticed that this mod in a full RO/RSS/RP0 installation indicates a wrong vessel mass (even negative) and a wrong placement of center of mass indicator (at least in SPH) when B9 procedural wings or some stock control surfaces are used in a craft. I'm not sure what mod is conflicting...

**Comment by m4v** [comment]
Wait until KSP 1.1 and report back, that issue is related to some shortcomings of KSP that 1.1 may or may not fix.
