### ISSUE TITLE
RCSBuildAid button behave weirdly...

### ISSUE THREAD

**Issue by Galenmacil** [m4v/RCSBuildAid#34]
When loading a game and returning to the main menu, the button is visible on the top right. Also, the options for choosing stock app button or Blizzy's toolbar are greyed out and editing the config file to force it doesn't work. Finally, the button is visible on the KSC center screen and clicking it generate an exception.

**Comment by Kerbas-ad-astra** [comment]
Greying out the stock/blizzy toolbar switch is deliberate, as Blizzy's toolbar wasn't yet updated when m4v was updating RCSBA.
