### ISSUE TITLE
CoM markers appearing after switching from crew/action groups tabs in VAB without build aid on

### ISSUE THREAD

**Issue by Nebulon-BFrigateFTW** [m4v/RCSBuildAid#35]
The little menu window does not appear, just the two markers. Clicking the build aid button after switching the VAB tabs results in the full thing with the menu and all, and then things behave as expected from then on.
Happening in KSP 1.1, 1.1.2, 1.1.3, 1.2, and 1.2.1 whenever I've used the mod.

**Comment by m4v** [comment]
I think this was fixed.
