### ISSUE TITLE
[KSP 1.2.2] DCoM doesn't compute for fuel priority

### ISSUE THREAD

**Issue by Xyphos** [m4v/RCSBuildAid#37]
I've noticed that the DCoM assumes that all fuel tanks drain equally, ignoring fuel priority.
some tanks are reserve tanks, they don't always get used up and should be considered "dry mass" even if they're full.

**Comment by m4v** [comment]
The DCoM doesn't assume that all fuel tanks drain equally, just that all fuel tanks are empty. There's #16 but at this point is not going to be implemented.

For your user case you can lock the fuel of the reserve tanks and the DCoM will assume they are full.
