### ISSUE TITLE
ksp 1.3

### ISSUE THREAD

**Issue by 0142929** [m4v/RCSBuildAid#39]
hello.
this very cool mod not working in ksp 1.3 :)
looks like something changed in new ksp,
can not click rcsbuildaid's button in vab

**Comment by andrewcchen** [comment]
I recompiled the binary, you can get it [here](https://github.com/andrewcchen/RCSBuildAid/releases/download/v0.9.1-ksp1.3/RCSBuildAid.dll). Just replace `RCSBuildAid.dll` with this.

**Comment by 0142929** [comment]
it works ^ ^
