### ISSUE TITLE
CoM marker does not track items in KIS Inventory

### ISSUE THREAD

**Issue by TonkaCrash** [m4v/RCSBuildAid#42]
Issue described in more detail in [KSP forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/149848-14-kerbal-inventory-system-kis-v114/&do=findComment&comment=3426553)

As items are added into a KIS storage container the Center of Mass marker generated by RCSBuildAid does not change with the added mass. The stock CoM marker does not have an issue with this.

**Comment by m4v** [comment]
This seems fixed now.
