### ISSUE TITLE
Style.cs modifies GUI.skin, causing problems for other mods

### ISSUE THREAD

**Issue by todi** [m4v/RCSBuildAid#44]
This is a old bug mentioned previously on the [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/33124-110x-rcs-build-aid-v102/&do=findComment&comment=3097091). LGG fixed it in his fork with this commit: https://github.com/linuxgurugamer/RCSBuildAid/commit/421201a464bd8b99f1506800a796dc8789d339e4. It is still there in your new versions.

**Comment by m4v** [comment]
thanks for the report.
